export const SONGS = [
    {
      id: '1',
      title: 'Du Demon',
      artist: 'Soolking',
      image: 'https://upload.wikimedia.org/wikipedia/en/8/89/Fruit_du_d%C3%A9mon_cover.png',
    },
    {
      id: '2',
      title: 'Laung Laachi',
      artist: 'Ammy Virk, Neeru Bajwa',
      image: 'https://a10.gaanacdn.com/images/albums/92/2180592/crop_480x480_2180592.jpg',
    },
    {
      id: '3',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      image: 'https://upload.wikimedia.org/wikipedia/en/4/45/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png',
    },
    {
      id: '4',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      image: 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    },
    {
      id: '5',
      title: 'Levitating',
      artist: 'Dua Lipa',
      image: 'https://upload.wikimedia.org/wikipedia/en/0/04/Dua_Lipa_-_Levitating.png',
    },
    {
      id: '6',
      title: 'Fruit Du Demon',
      artist: 'Soolking',
      image: 'https://upload.wikimedia.org/wikipedia/en/8/89/Fruit_du_d%C3%A9mon_cover.png',
    },
    {
      id: '7',
      title: 'Laung Laachi',
      artist: 'Ammy Virk, Neeru Bajwa',
      image: 'https://a10.gaanacdn.com/images/albums/92/2180592/crop_480x480_2180592.jpg',
    },
    {
      id: '8',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      image: 'https://upload.wikimedia.org/wikipedia/en/4/45/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png',
    },
    {
      id: '9',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      image: 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    },
    {
      id: '10',
      title: 'Levitating',
      artist: 'Dua Lipa',
      image: 'https://upload.wikimedia.org/wikipedia/en/0/04/Dua_Lipa_-_Levitating.png',
    },
    {
      id: '11',
      title: 'Fruit Du Demon',
      artist: 'Soolking',
      image: 'https://upload.wikimedia.org/wikipedia/en/8/89/Fruit_du_d%C3%A9mon_cover.png',
    },
    {
      id: '12',
      title: 'Laung Laachi',
      artist: 'Ammy Virk, Neeru Bajwa',
      image: 'https://a10.gaanacdn.com/images/albums/92/2180592/crop_480x480_2180592.jpg',
    },
    {
      id: '13',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      image: 'https://upload.wikimedia.org/wikipedia/en/4/45/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png',
    },
    {
      id: '14',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      image: 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    },
    {
      id: '15',
      title: 'Levitating',
      artist: 'Dua Lipa',
      image: 'https://upload.wikimedia.org/wikipedia/en/0/04/Dua_Lipa_-_Levitating.png',
    },
    {
      id: '16',
      title: 'Fruit Du Demon',
      artist: 'Soolking',
      image: 'https://upload.wikimedia.org/wikipedia/en/8/89/Fruit_du_d%C3%A9mon_cover.png',
    },
    {
      id: '17',
      title: 'Laung Laachi',
      artist: 'Ammy Virk, Neeru Bajwa',
      image: 'https://a10.gaanacdn.com/images/albums/92/2180592/crop_480x480_2180592.jpg',
    },
    {
      id: '18',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      image: 'https://upload.wikimedia.org/wikipedia/en/4/45/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png',
    },
    {
      id: '19',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      image: 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    },
  ];